from emailer import Emailer
from formatter import DataFormatter
from parser import Parser
from config import Config


class Processor():

    def __init__(self):
        self.master_data = self._parse()

    def _parse(self):
        parser = Parser()
        master_data = parser.parse()
        return master_data

    def format(self):
        data_formatter = DataFormatter(self.master_data)
        message = data_formatter.get_formatted_data()
        return message

    def email(self):
        data_formatter = DataFormatter(self.master_data)
        message = data_formatter.create_report()
        emailer = Emailer()
        emailer.send_mail(
            'Report generated by python script', message, Config.USE_LOCALHOST)

if __name__ == '__main__':
    processor = Processor()
    processor.email()
